CREATE TABLE IF NOT EXISTS fato_incidente_predictfy (
        incident_feature_id CHAR(64) NOT NULL PRIMARY KEY,
        hora TINYINT NOT NULL,
        dia_semana TINYINT NOT NULL,
        mes TINYINT NOT NULL,
        trimestre TINYINT UNSIGNED NOT NULL,
        prioridade_codigo VARCHAR(2) NOT NULL,
        prioridade_desc VARCHAR(20) NOT NULL,
        ola_limite_horas SMALLINT UNSIGNED NOT NULL,
        is_horario_comercial BIT NOT NULL,
        is_fim_de_semana BIT NOT NULL,
        periodo_dia_desc VARCHAR(12) NOT NULL,
        lag_1d DECIMAL(18,4) NULL,
        lag_7d DECIMAL(18,4) NULL,
        rolling_7d DECIMAL(18,4) NOT NULL,
        rolling_30d DECIMAL(18,4) NOT NULL,
        media_movel_delta DECIMAL(18,4) NOT NULL,
        tendencia_volume VARCHAR(10) NOT NULL,
        is_feriado BIT NOT NULL,
        contexto_calendario VARCHAR(12) NOT NULL,
        target_ola BIT NOT NULL,
        ocorrencia_ola VARCHAR(8) NOT NULL,
        origem_dado VARCHAR(64) NOT NULL,
        arquivo_origem VARCHAR(128) NOT NULL,
        data_processamento_utc DATETIME(3) NOT NULL,
        INDEX ix_fato_incidente_analise (mes, dia_semana, ocorrencia_ola),
        INDEX ix_fato_incidente_prioridade (prioridade_codigo, tendencia_volume)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
